### ISSUE TITLE
How do I configure to collect resources in different maps?

### ISSUE THREAD

**Issue by pedrosarkis** [AXeL-dev/Dindo-Bot#15]
I'm having issues to collect resources in different maps, I can create one map file ( in bot) and one path file, but how can I set up to change the map after the resources's over , change the map and then collect the resources of this other map ?

**Comment by AXeL-dev** [comment]
Simply use a movement action after the collect action, i'm not sure how your path file look like & it would be better if you can share it, but here is a simple example of what it should be like:
```
Collect(map=[7,-23],store_path=paths/store/from_[7,-23]_to_bank_astrub.path)
Move(RIGHT)
Collect(map=[9,-23],store_path=paths/store/from_[9,-23]_to_bank_astrub.path)
Move(DOWN)
Move(LEFT)
```
In the example above the bot will collect the first map & when it ends it will move 1 time right then start collecting the second map then continue moving till the end of the path file.

You can find more path file examples [here](https://github.com/AXeL-dev/Dindo-Bot/tree/master/paths).

**Comment by pedrosarkis** [comment]
Hey, thanks for the answer, I did what u said, but i'm still having issues, I'm adding two files as example, and a video of what I'm doing. 

The bot skips almost all the resources on the map, and jumps directly to "move right" (And the bot doesn't move,by the way)

https://youtu.be/t8pgfXJV1_E

My path file 
` Collect(map=[1,23] teste,store_path=None)
Move(RIGHT)
Collect(map=[2,23] teste,store_path=None) 
`

My maps file 
"[2,23] teste":[
      {
         "y":376,
         "x":1375,
         "height":1080,
         "color":"(255, 209, 35)",
         "width":3286
      },
      {
         "y":355,
         "x":1377,
         "height":1080,
         "color":"(255, 232, 42)",
         "width":3286
      },
      {
         "y":140,
         "x":60,
         "height":700,
         "color":"(255, 208, 36)",
         "width":900
      },
      {
         "y":193,
         "x":54,
         "height":700,
         "color":"(132, 115, 14)",
         "width":900
      },
      {
         "y":542,
         "x":83,
         "height":700,
         "color":"(138, 137, 21)",
         "width":900
      },
      {
         "y":554,
         "x":127,
         "height":700,
         "color":"(255, 255, 175)",
         "width":900
      },
      {
         "y":542,
         "x":177,
         "height":700,
         "color":"(255, 203, 36)",
         "width":900
      }
   ],

   "[1,23] teste":[
      {
         "y":430,
         "x":134,
         "width":900,
         "color":"(255, 255, 74)",
         "height":700
      },
      {
         "y":463,
         "x":71,
         "width":900,
         "color":"(255, 238, 41)",
         "height":700
      },
      {
         "y":494,
         "x":19,
         "width":900,
         "color":"(222, 146, 12)",
         "height":700
      },
      {
         "y":688,
         "x":1343,
         "width":3286,
         "color":"(255, 211, 37)",
         "height":1080
      },
      {
         "y":403,
         "x":73,
         "width":900,
         "color":"(182, 105, 5)",
         "height":700
      }

**Comment by AXeL-dev** [comment]
The first thing i noticed on your video, is that the game window is way far from the bot window, which shouldn't be the case, since the bot will automatically fit/resize the window to be scotched to the bot window, so i don't know if this is an issue related to the bot, or maybe something else.

The second thing, is the width & height of the map points/coordinates on your map file, they are not the always same, sometimes it's :
```diff
{
  "y":494,
  "x":19,
+ "width":900,
  "color":"(222, 146, 12)",
+ "height":700
},
```
& other times it's :

```diff
{
  "y":688,
  "x":1343,
+ "width":3286,
  "color":"(255, 211, 37)",
+ "height":1080
},
```
And this is not normal too. So, i don't know if you are use multi screens, or an HD/Big screen, but the issue may be related to this. Have you or can you try on a laptop with normal screen so we can confirm that?

**Comment by pedrosarkis** [comment]
I figured out that I was first opening the bot, and only then the game (yes, i'm dumb) that's why the bot window as way far from the game window, and yes, I have multi screen,  I've tested with only one and the problem with the width and heights don't happen anymore. 

I noticed two things, the bot only worked correctly, when I changed the preferences from "Check resources color" to "Save dragondindes image" (I have no idea of what that means, but i like it haha). 

And just for u to know in your future updates, the bots stops completely when it happens to click on myself , like this : 

![image](https://user-images.githubusercontent.com/22531754/76693295-72041900-6641-11ea-9533-032686f0cef9.png)

Thank you for all the support <3

**Comment by AXeL-dev** [comment]
> I noticed two things, the bot only worked correctly, when I changed the preferences from "Check resources color" to "Save dragondindes image" (I have no idea of what that means, but i like it haha).

In fact `Save dragondindes image` will only work with dragodindes rearing actions (like the enclos action), so what works in fact is that you've disabled the `Check resources color`, which tells the bot to not check the resources color before clicking on them.

> And just for u to know in your future updates, the bot stops completely when it happens to click on myself , like this :

This is somehow expected since the bot works by detecting changes on the screen, so if ever your game character stands without moving, the bot will simply understand that as "nothing happened" & will stop to avoid doing a stupid thing, but anyway, this is something that surely needs to be improved.

Finally, i only try to help as i can, & thank you too for exposing such issues, which may help improving the bot in the future :wink:
