### ISSUE TITLE
ValueError: Namespace Wnck not available for version 3.0

### ISSUE THREAD

**Issue by Gambl3r08** [AXeL-dev/Dindo-Bot#4]
For problems with manjaro I installed Antergos and throw the next error:

`
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from gui.main import BotWindow
  File "/home/gambl3r/Descargas/Dindo-Bot-master/gui/main.py", line 7, in <module>
    from lib import tools, logger, data, parser, settings, accounts, maps
  File "/home/gambl3r/Descargas/Dindo-Bot-master/lib/tools.py", line 8, in <module>
    gi.require_version('Wnck', '3.0')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 131, in require_version
    (namespace, version))
ValueError: Namespace Wnck not available for version 3.0

`

**Comment by AXeL-dev** [comment]
hum, this means that the python Wnck package is missing in antergos, & i guess the package name is [python2-wnck](https://www.archlinux.org/packages/extra/x86_64/python2-wnck/).
So you can try installing it using: `sudo pacman -S python2-wnck`
Otherwise, if you want to avoid new/next errors related to missing package(s), i invite you to try [ubuntu budgie 18.04](https://ubuntubudgie.org/blog/2018/03/08/18-04-release-notes) (a debian based linux distribution) or [Xubuntu](https://xubuntu.org/news/18-04-1-released/) if you like the XFCE Desktop environment like in Manjaro.
